app.voice.asset-root=../PokemonBattleTool/animal_crossing_voice
app.voice.output-dir=/tmp

# https://ja.quarkus.io/guides/deploying-to-google-clou より
# App Engine にデプロイするのに必要らしい
quarkus.package.jar.type=uber-jar